
# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/19eKVNRzY_h56ASeLxu-aR_dTOkHbzrA6Msg57F1_ebs"

type = "service_account"
project_id = "grounded-jetty-338508"
private_key_id = "287617882850ef4ba05c891e17e7d08ab9cf8d9c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDaGgUQ6X8tMam2
i5fZ3kX8Zcx66PSrKlizMgZl8WpAdzgDECL4AUSJtVaunbPXDID+R9DWy9bPGEZQ
VPSXOlNvU6r0z0kvopbYSSw+p2iuewz/x6xRnEhTMARIwJas5nhEuBgrvqMTWPvl
biyAFuunJIYO4bLUmCbHQp9EB83u/zTCUL8qKkFIa63kHi8sXY7wJLNzOm3Cu+tc
rhnZmHLWx4Bgd6ip7+gGESs3v4JZ8toiNJgyS8hPN9e2J4UoOhumOupmyiYu0ddV
J3QutZopkE8UNCpuIYA0tU5vvqUwmjbP4E+rfSTnRECmC5F73dGtELOubeHw5QwD
DY1agF+PAgMBAAECggEAI87x1f0ALGNjAd2ZaOPdibsM/4EP6qphNcqY0lP4pezs
/VPA6gcLQbDMMo8h38TlyNnxp9J/yjCqGrZYEhw5ZqXOA7OkyHVhXtFkukSyIzOA
xt35pMyL81yG14sHMgwE4wN2tHfwPlT1xo14MO+ScTbF69uSiOUSONTvYTQG0541
MH3u4KDMK0i7PuO8OdRGjQ4YAipQAHMxnpNEjjWItGP2bYgYmIuV8mbwoh4nEK2c
F7CkeqC+FSpFDUrgotEpT0jCyYpwb2m4eJDcofkZl+0ktxgJFqrjDHE+mJInqikB
1OtD/N63Cl9XAlW9T/wXU9gAf+SFD9VSAMTKDu1KAQKBgQD/TiCceAyNa/aCdlf2
IcRC+eXr6n2fR1Bt0OCVul/1iiV0fe/URm4a/IgZVXEV5PCWYEs9kdYi7qUnguSU
XfZ/LoEkutkt4Zj0JSd9xS9/MCEaGsFajV4hy2s2btVKqo6TwnnNUPEWwI3xaZLt
RbEBIyfdKgnUo6leu48E/PKAYQKBgQDasfj0GRhCUxwgx3I2DdKUESmIJYSbN2T4
RRKIdupJrEKfKxVK865gBf4+ZaqEd4/zT2hl+BRePex5NDb/sOgnBUkLeDx8WYrs
plszD71oaoXvyDqosy25mPYVfGu6KMP55O2gCuxFg0DXGGKSLxlqthVF3YnPh5vx
RjDPFNyl7wKBgQCgOL68k5aFFlFA9NYlEHHj+oKxuJqX4CB4mpKnRKy+IrF41yQw
2vZ0lzEufPGYZPIb3Vi6zhBOIeih0EJ1Xja5AE1p6J0tbxwXdE3BX4N8VY8gm9Pm
aTu/B7NEGPBgiIMr9euMz5RNzBAIhlH/+DGqXg7BfIVo3kEHw7twzPG/YQKBgQCs
iOxX59Rzvw3Z7n/0lUMk/cU+XBsaOcG2/Qd6EhcUuIp2+I5763QO3auPnrXAfHNd
CbDbgbTQBRqjJMafQvpkjo7qNZnCoQIxYa1hw3EzB5dTbSyaG4JfgoXivZ5f5/l1
FV9DfFqbHMny6JIbsnzi63QtAnLO/7XPzAiF13eckQKBgQCTRDHM06R2Itt9IT0g
oDS8RZs2ehhtUaZEHcfacISosaWNWb+B0gTBK5fA5FfPmkGmezrbmbJ4XmlVnI3T
bDjq7nHHExm75MHLQL70fPbZll2YtUA0qNL7THi6N7njrLWiIysDQ9Kk7P0xmsmQ
9lqXzRlE1X5/aT7X/AyYB9fcrQ==
-----END PRIVATE KEY-----
"""
client_email = "wg-gesucht-01@grounded-jetty-338508.iam.gserviceaccount.com"
client_id = "108795020391978097753"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/wg-gesucht-01%40grounded-jetty-338508.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
